application:
  version: 1.0.0
  title: demo

spring:
  profiles:
    active: local

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true # spring-boot-devtools: live-reload

# App Properties
litsynp:
  app:
    jwtSecret: litsynpSecretKey
    jwtExpirationMs: 86400000
